name: 'Let me google that for you action'
description: 'Add this action to your repository to auto reply to issues with a let me google that for you link.'
inputs:
    github-token:  # id of input
        description: 'Github Token'
        required: true
    field-to-query: #id of input
        description: 'Use the `"title"` or `"body"` as options to search. Default: `"title"`'
        required: true
        default: 'title'
runs:
    using: 'node12'
    main: 'dist/index.js'
