name: AutoRespondToIssues

on: 
  issues:
    types: [opened]

jobs:
  autoRespond:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rdlucas2/lmgtfy-action@v0.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #field-to-query: 'body' #default is title